<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFq9tolv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFq9tolv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFq9tolv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFq9tolv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFq9tolv\appProdProjectContainer([
    'container.build_hash' => 'Fq9tolv',
    'container.build_id' => '8186c991',
    'container.build_time' => 1581604531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFq9tolv');
